spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
oauth2:
  provider:
    google:
      client-id: ${ GOOGLE_CLIENT_ID }
      client-secret: ${ GOOGLE_CLIENT_SECRET }
      redirect-uri: http://localhost:8080/login/oauth2/code/google
      token-uri: https://oauth2.googleapis.com/token
      user-info: https://www.googleapis.com/oauth2/v2/userinfo
    kakao:
      client-id: ${ KAKAO_CLIENT_ID }
      client-secret: ${ KAKAO_CLIENT_SECRET }
      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
      token-uri: https://kauth.kakao.com/oauth/token
      user-info: https://kapi.kakao.com/v2/user/me

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
